[package]
name = "yoannrompion/basegame"
version = "0.1.0"
registry = "https://github.com/Rivrs-Roblox/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.7.0"
Roact = "roblox/roact@1.4.4"
Trove = "sleitnick/trove@1.3.0"
Input = "sleitnick/input@2.3.0"
Signal = "sleitnick/signal@2.0.1"
Shake = "sleitnick/shake@1.1.0"
Timer = "sleitnick/timer@1.1.2"
RoactRodux = "roblox/roact-rodux@0.3.0"
Rodux = "roblox/rodux@3.0.0"
Hooks = "kampfkarren/roact-hooks@0.3.0"
Roduxhooks = "solarhorizon/rodux-hooks@0.3.1"
RoactSpring = "chriscerie/roact-spring@^1.1.6"
Preloader = "release/preloader-module@1.0.5"
#Animation = "rivrs/animation-module@0.1.22"
Sound = "release/sound-module@0.0.11"
VFX = "release/vfx-module@0.0.11"
Quest = "release/quests-module@1.1.2"
uiModule = "release/ui-module@3.1.1"
funnelsModule = "release/funnels-module@1.2.0"
#popupModule = "release/popup-module@1.0.0"
fightModule = "release/fight-module@1.0.0"
actionModule = "release/actions-module@1.0.2"
petsModule = "release/pets-module@1.4.4"
rivrs-eggs-module = "rivrs/new-eggs-module@0.0.5"
rivrs-group-rewards-module = "rivrs/new-group-rewards-module@0.0.13"
goldMachineModule = "release/goldmachine-module@1.0.1"