[package]
name = "release/vfx-module"
version = "0.0.11"
registry = "https://github.com/Rivrs-Roblox/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.5.1"
signal = "sleitnick/signal@2.0.1"
core = "release/core-module@^1"
Streamable = "sleitnick/streamable@1.2.4"
