[package]
name = "rivrs/new-group-rewards-module"
version = "0.0.13"
registry = "https://github.com/Rivrs-Roblox/wally-index"
realm = "shared"

[dependencies]
#knit = "sleitnick/knit@1.5.1"
Signal = "sleitnick/signal@^2"
