[package]
name = "release/ui-module"
version = "3.1.1"
registry = "https://github.com/Rivrs-Roblox/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.5.1"
core = "release/core-module@^1"
roact = "roblox/roact@1.4.4"
rodux = "roblox/rodux@3.0.0"
roact-rodux = "roblox/roact-rodux@^0"
roact-hooks = "kampfkarren/roact-hooks@^0"
rodux-hooks = "solarhorizon/rodux-hooks@^0"
roact-spring = "chriscerie/roact-spring@2.0.0"
